apiVersion: v1
kind: Service
metadata:
  name: hostname
  labels:
    app: hostname
spec:
  ports:
    - port: 8080
      name: http
  clusterIP: None
  selector:
    app: hostname
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: hostname
spec:
  selector:
    matchLabels:
      app: hostname
  serviceName: "hostname"
  replicas: 2
  template:
    metadata:
      labels:
        app: hostname
    spec:
      containers:
        - name: hostname
          image: registry.gitlab.com/seongjindo/commonapi:latest
          ports:
            - containerPort: 8080
              name: http
          volumeMounts:
            - name: data
              mountPath: /data
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 1Gi

